### ISSUE TITLE
First keypress not working

### ISSUE THREAD

**Issue by Matoto2** [zhorton34/vuejs-form#20]
**Describe the bug**
Hi there! I came across an annoying issue with the initialization of my inputs. It seems like the inputs won't let you write the first character you enter in them the first time you type in them.

**To Reproduce**
1. Go to https://codepen.io/zhorton34/pen/zYvWZYz
2. Click on any input
3. Type only one character. Nothing happens. Type again, characters now show.

**Expected behavior**
Should display first keypressed character

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 86.0.4240.183

**Comment by zhorton34** [comment]
Closing ticket ~ new merge request fixes this bug thanks to @vaugenwake

See pull request for more details
https://github.com/zhorton34/vuejs-form/pull/21
