### ISSUE TITLE
Regex /Not-Regex rule is not working

### ISSUE THREAD

**Issue by sudip571** [zhorton34/vuejs-form#22]
I used the regex rule as mentioned in the documentation but it throws an error as shown in the attached screenshot
![formerror](https://user-images.githubusercontent.com/24267838/116001662-3940bc80-a615-11eb-8982-8561d4ad7c1d.PNG)

I tried to find out the reason and I might be wrong but I think the reason is .... ok I will explain with the help of screenshot attached below
![causeerror](https://user-images.githubusercontent.com/24267838/116001763-e3204900-a615-11eb-8a7c-3f814f8292cc.PNG)
 
It was expected to be working like the one, underlined with green colour, but in the **regex/not_regex** function, the **parameters[0]** (underlined with red colour) gives string value( e.g **"/^.+@.+$/i"**). And of course, **string.test** is not the function. So it gives the error.

If I have misunderstood things, please let me know. Also, Is there any other solutions to work with Regex ?

**Comment by zhorton34** [comment]
Hey @sudip571, this is the wrong repo for this issue. 

The validation rules have their own repo to keep the tests and codebase much more concise. Please move the contents of this issue over here ~ https://github.com/zhorton34/vuejs-validators/issues

Closing this issue out on this repository as the code that you're referencing is not fixable within this vuejs-form code base.
